# Generated by Django 5.1.7 on 2026-03-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gcal_access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gcal_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='gcal_refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gcal_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
