# Generated by Django 5.1.7 on 2026-03-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='gcal_event_id_doctor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='gcal_event_id_patient',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
